language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - DEPS=latest
  - DEPS=lowest

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-lowest ; fi

script:
  - composer test:units

jobs:
  include:
    - stage: test
      name: 'Lint Syntax'
      php: 7.3
      script:
        - composer update --no-interaction
        - composer lint:syntax
    - stage: test
      name: 'Lint Style'
      php: 7.3
      script:
        - composer update --no-interaction
        - composer lint:style
    - stage: test
      name: 'Coverage'
      php: 7.3
      script:
        - composer update --no-interaction
        - composer test:coverage
    - stage: test
      name: 'Mutations'
      php: 7.2
      script:
        - composer update --no-interaction
        - composer require --dev infection/infection
        - vendor/bin/infection
    - stage: test
      name: 'ZF2 Latest'
      php: 7.2
      script:
        - cd test/ZF2
        - composer update --no-interaction
        - vendor/bin/phpunit
    - stage: test
      name: 'ZF2 Lowest'
      php: 7.2
      script:
        - cd test/ZF3
        - composer update --no-interaction
        - vendor/bin/phpunit
    - stage: test
      name: 'ZF3 Latest'
      php: 7.2
      script:
        - cd test/ZF2
        - composer update --no-interaction --prefer-lowest
        - vendor/bin/phpunit
    - stage: test
      name: 'ZF3 Lowest'
      php: 7.2
      script:
        - cd test/ZF3
        - composer update --no-interaction --prefer-lowest
        - vendor/bin/phpunit

notifications:
  email: false
